# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-21 18:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20170221_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='student_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='students.Group', verbose_name='Group'),
        ),
    ]
